apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-demo-app
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness-demo-app
  template:
    metadata:
      labels:
        app: harness-demo-app
    spec:
      containers:
        - name: harness-demo-app
          image: cristianlajos/harness-demo-app:<+artifact.tag>
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: harness-demo-app
  namespace: production
spec:
  selector:
    app: harness-demo-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
    - name: nodeport
      port: 8080
      targetPort: 5000
      nodePort: 30080
  type: NodePort
