apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-demo-app
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness-demo-app
  template:
    metadata:
      labels:
        app: harness-demo-app
    spec:
      containers:
        - name: harness-demo-app
          image: {{.Values.image}}
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: harness-demo-app
  namespace: staging
spec:
  selector:
    app: harness-demo-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
